version: '3'
services:
  frontend:
    build: .
    ports:
      - "7000:80"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/subscriptions:/app/subscriptions
    env_file:
      - ./server/.env